Updated to use snake case
Griffin-Brome/cosc499-group pull request #5
Opened 2020-09-21 17:22 UTC by KazeShikaru

2020-09-21 17:24 UTC, Griffin-Brome approved these changes
lgtm

2020-09-21 18:05 UTC, pat53 submitted a review, later dismissed

2020-09-21 19:49 UTC, pat53 submitted a review, later dismissed

2020-09-22 01:20 UTC, Griffin-Brome requested changes

2020-09-22 01:20 UTC, Griffin-Brome commented on README.md
> +### Selection Sort
Not sure what you meant to do here. But Bubble sort should be its own category. You have overwritten the description of Selection sort instead

2020-09-22 03:21 UTC, Griffin-Brome submitted a review, later dismissed

2020-09-22 14:53 UTC, pat53 approved these changes

2020-09-22 17:12 UTC, merged